# 使用GitHub Pages默认主题 - Cayman
theme: jekyll-theme-cayman
title: ArXiv Q-Fin & 搜推 Daily
description: "每日自动检索和总结arXiv论文的工具，使用AI生成论文摘要。\n本页面专注于量化金融(q-fin)和搜索推荐(搜推)相关的最新研究。"
author: dong-zehao

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  math_engine: nil